import { generateMappings } from "../generalMappings.js"

export const level1Mappings = generateMappings("grass");
export const level1Layout = [
  [
    "                               i                                                                                                                                       ",
    "                              @                                                                                                                                        ",
    "                             9aab                                                                                                                                      ",
    "                             cdde                                                                                                                                      ",
    "                             cdde                                                                                                                                      ",
    "                             cdde                                                                                                                                      ",
    "                             cdde                                                                                                                                      ",
    "                             cdde                                                                                                                                      ",
    "                             cdde                                                                                                                                      ",
    "                             cdde                                                                                                                                      ",
    "                                                                                                                                                                       ",
    "                                                                                                                                                                       ",
    "                                                                                                                                                                       ",
  ],
  [
    "                                                                                                                           ",
    "                                                                                                                           ",
    "                                                                                                                           ",
    "                                  @           @@                                                                           ",
    "                               9aab          9aab                                @@                                        ",
    "                           @   cdde          cdde                      @   9aaaboooo9aaab                                  ",
    "                          9aab cdde          cdde 9aab               9aab  cddde    cddde                                  ",
    "                          cdde cdde          cdde cdde               cdde  cddde    cddde   h g                            ",
    "                          cdde cdde          cdde cdde          @    cdde  cddde    cddde    @                             ",
    "                   0111111111111112     @    cdde11111111111112oooo0111111111112    011111111112                           ",
    "                   3444444444444445          cdde44444444444445    3444444444445    344444444445                           ",
    "                   6777777777777778          cdde77777777777778    6777777777778    677777777778                           ",
  ],
  [
    "                                                                                                                           ",
    "                                                                                                                           ",
    "                                                                                                                           ",
    "                                                                                                                           ",
    "                                                                                                                           ",
    "                                                                                                                           ",
    "                                                                                                                           ",
    "                                                                                        9aab                               ",
    "                                                   @@                        @@      @@ cdde                               ",
    "                                                                                                                           ",
    "                                                                                                                           ",
    "                                                                                                                           ",
  ],
]